# Generated by Django 4.1 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObituaryInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID')),
                ('chicken_flock_id', models.CharField(max_length=32, verbose_name='雞群ID')),
                ('chicken_seedling_number', models.CharField(max_length=255, verbose_name='雞苗數量')),
                ('chicken_seedling_age', models.CharField(max_length=255, verbose_name='雞苗年齡')),
                ('incubation_date', models.CharField(max_length=255, verbose_name='孵化日期')),
                ('death_number', models.CharField(max_length=255, verbose_name='死亡數量')),
                ('eliminate_number', models.CharField(max_length=255, verbose_name='淘汰數量')),
                ('data_time', models.CharField(max_length=10, verbose_name='數據時間')),
                ('data_version', models.IntegerField(verbose_name='數據版本')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增時間')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新時間')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='數據是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'obituary_info',
                'unique_together': {('id', 'data_time', 'data_version')},
            },
        ),
    ]
