# Generated by Django 5.0.1 on 2024-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionnaireScoreAddInfo",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID,數據庫主鍵",
                    ),
                ),
                ("id", models.CharField(max_length=32, verbose_name="數據ID")),
                (
                    "farm_id",
                    models.CharField(max_length=32, verbose_name="農場ID,問卷歸屬人ID"),
                ),
                ("user_id", models.CharField(max_length=32, verbose_name="用户ID,答題人ID")),
                ("total_score", models.IntegerField(verbose_name="總得分")),
                ("data_version", models.IntegerField(verbose_name="數據版本")),
                ("create_time", models.CharField(max_length=50, verbose_name="新增時間")),
                ("create_by", models.CharField(max_length=32, verbose_name="新增人")),
                ("update_time", models.CharField(max_length=50, verbose_name="更新時間")),
                ("update_by", models.CharField(max_length=32, verbose_name="更新人")),
                (
                    "deleted",
                    models.BooleanField(
                        default=0, max_length=32, verbose_name="數據是否已删除[0:未删除,1:已删除]"
                    ),
                ),
            ],
            options={
                "db_table": "questionnaire_score_info",
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireScoreQueryInfo",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID,數據庫主鍵",
                    ),
                ),
                ("id", models.CharField(max_length=32, verbose_name="數據ID")),
                (
                    "farm_id",
                    models.CharField(max_length=32, verbose_name="農場ID,問卷歸屬人ID"),
                ),
                ("user_id", models.CharField(max_length=32, verbose_name="用户ID,答題人ID")),
                (
                    "username",
                    models.CharField(
                        max_length=32, verbose_name="用户ID,答題人賬號,數據庫没有對應鍵,sql進行查詢"
                    ),
                ),
                ("total_score", models.IntegerField(verbose_name="總得分")),
                ("data_version", models.IntegerField(verbose_name="數據版本")),
                ("create_time", models.CharField(max_length=50, verbose_name="新增時間")),
                ("create_by", models.CharField(max_length=32, verbose_name="新增人")),
                ("update_time", models.CharField(max_length=50, verbose_name="更新時間")),
                ("update_by", models.CharField(max_length=32, verbose_name="更新人")),
                (
                    "deleted",
                    models.BooleanField(
                        default=0, max_length=32, verbose_name="數據是否已删除[0:未删除,1:已删除]"
                    ),
                ),
            ],
        ),
    ]
