# Generated by Django 4.1 on 2025-03-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireScoreInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='數據ID')),
                ('farm_id', models.CharField(max_length=32, verbose_name='農場ID,問卷歸屬人ID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID,答題人ID')),
                ('total_score', models.IntegerField(verbose_name='總得分')),
                ('data_version', models.IntegerField(verbose_name='數據版本')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增時間')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新時間')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='數據是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'questionnaire_score_info',
            },
        ),
        migrations.DeleteModel(
            name='QuestionnaireScoreAddInfo',
        ),
        migrations.RemoveField(
            model_name='questionnairescorequeryinfo',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='questionnairescorequeryinfo',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='數據ID'),
        ),
        migrations.AlterField(
            model_name='questionnairescorequeryinfo',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名稱,答題人賬號,數據庫没有對應鍵,sql進行查詢'),
        ),
    ]
