# Generated by Django 4.1 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('text', models.CharField(max_length=5000, verbose_name='消息内容')),
                ('title', models.CharField(max_length=255, verbose_name='消息標題')),
                ('msg_time', models.CharField(max_length=255, verbose_name='消息時間')),
                ('resources_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='資源ID')),
                ('create_time', models.CharField(max_length=50, verbose_name='更新時間')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新時間')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='數據是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'notice_info',
            },
        ),
    ]
