# Generated by Django 4.1 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='資源名稱')),
                ('path', models.TextField(verbose_name='資源存放路徑')),
                ('resources_type', models.CharField(max_length=2, verbose_name='資源類型[0:消息附件],1:表格附件')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件類型')),
                ('person', models.CharField(max_length=32, verbose_name='所屬管理員ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備注')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增時間')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新時間')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='數據是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'resources_info',
            },
        ),
    ]
