# Generated by Django 4.1 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('shop_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='店铺ID')),
                ('name', models.TextField(verbose_name='商品名稱')),
                ('price', models.IntegerField(verbose_name='商品單價,單位分')),
                ('weight', models.IntegerField(verbose_name='商品重量,單位分')),
                ('type', models.CharField(blank=True, max_length=1, null=True, verbose_name='商品類型')),
                ('number', models.CharField(blank=True, max_length=1, null=True, verbose_name='商品數量')),
                ('resources_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='資源ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備注')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增時間')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新時間')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='數據是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'commodity_info',
            },
        ),
    ]
